terra-jupyter-bioconductor/README.md

Add README.md to the terra-jupyter-bioconductor image

---

terra-jupyter-bioconductor/Dockerfile
terra-jupyter-r/Dockerfile

Based on a conversation with Justin and Qi, this change is being implemented. Tested on Leo locally.
cc @Qi77Qi

Make Bioconductor version more explicit for developers to see

---

README.md
build.sh
terra-jupyter-python/README.md

This conflicts with my other PR, but the merge will be trivial as I included the build.sh changes from that PR in this file as well, and simply added to it.

[IA-1332] Jc update build for docs

---

build.sh

Add support for adding the R and Python versions to the appropriate documentation files

[IA-1332] Jc lang version

---

config/conf.json
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Tests: look at DataBiosphere/leonardo#1145

[IA-1375] Remove apt-get upgrade

---

config/conf.json
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-base/scripts/kernel/kernel_bootstrap.sh
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile

https://broadworkbench.atlassian.net/browse/PROD-303

PROD-303 fix WORKSPACE_BUCKET

---

jenkins/Jenkinsfile

- job sends slack message on failure
- job records images it built in pr body

job upgrades

---

config/conf.json

Changes the static portion of the label in the UI for the base image from 'minimal' to 'base'

changing UI label

---

build.sh
jenkins/Jenkinsfile
scripts/utils.py

- fixes auth issues with old svc acct
- defensively stop containers in case job terminates at an undesirable time and leaves images dangling
- add debug output to gsutil cp

Debug build

---

config/conf.json
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile

https://broadworkbench.atlassian.net/browse/IA-1552
Didn't bump bioconductor image since it 0.0.8 hasn't been published successfully yet anyway

IA-1552 upgrade pandas

---

terra-jupyter-bioconductor/Dockerfile

Incomplete link

---

build.sh

https://broadworkbench.atlassian.net/browse/IA-1572
Pending `terra-jupyter-gatk` to be created

IA-1572 push gatk image to dockerhub as well

---

config/conf.json
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile

https://broadworkbench.atlassian.net/browse/IA-1608
Tested with https://github.com/DataBiosphere/leonardo/pull/1209

IA-1608 upgrade gatk version

---

config/conf.json
scripts/generate_version_docs.py

https://broadworkbench.atlassian.net/browse/IA-1555

IA-1555 flip on gatk

---

config/conf.json

Friends with https://github.com/DataBiosphere/leonardo/pull/1214

IA-1610 Include hail and bioc in the dataproc image

---

config/conf.json
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/custom/google_sign_in.js
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Also update all sub-images with the new base.
See https://broadworkbench.atlassian.net/browse/IA-1653

[IA-1653] Fix cookie setting in google_sign_in.js in terra-jupyter-base

---

config/conf.json

[Ticket](https://broadworkbench.atlassian.net/browse/IA-1596)
[Companion Leonardo PR](https://github.com/DataBiosphere/leonardo/pull/1306)

[IA-1596] Jenkins-ify Custom GCE Image Creation

---

build.sh
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-aou/README.md

This is basically terra-jupyter-gatk minus GATK, plus a few extra deps that AoU currently installs in the initialization script.
Sister Leo PR: https://github.com/DataBiosphere/leonardo/pull/1307

IA-1716 Define initial AoU docker image

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile

Update derived images to consume https://github.com/DataBiosphere/terra-docker/pull/113

[IA-1856] Update python derived images for pysam support

---

scripts/generate_version_docs.py

@sharmatime wanted to add this text. Need to fill in the date when the release date is known.
Opening this PR as a placeholder so I don't forget.

 label change for Legacy GATK image

---

config/community_images.json
scripts/generate_version_docs.py
scripts/utils.py

related PR https://github.com/DataBiosphere/terra-ui/pull/2189

[IA-2029] Adding support for community maintained images

---

config/conf.json
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile

Upgrading hail to version 0.2.50.

Upgraded hail to version 0.2.50

---

CONTRIBUTING.md

[No Ticket] Community image guide wording

---

build.sh

This PR introduces:
- Docker image security scan, if there are CRITICAL findings, the job will fail.

[Trivy] Add docker security scan

---

CONTRIBUTING.md

[no ticket] additional instruction

---

config/conf.json
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile

Updating hail from 0.2.54 to 0.2.57

Update hail to 0.2.57

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

**Do not merge**: Need to confirm whether the gatk commit hash is correct, or if I should hold for further changes.
AoU ticket: https://precisionmedicineinitiative.atlassian.net/browse/RW-5584
cc @Qi77Qi @ericsong @petesantos @ahaessly

Install plink and gatk jar on AoU docker image

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

This should massively reduce the resource requirements for building this image, per
- https://broadworkbench.atlassian.net/browse/IA-2221
- https://broadworkbench.atlassian.net/browse/DDO-752

AoU: Download gatk jar instead of building

---

CONTRIBUTING.md

Updating contributor guide with JIRA ticket reminder

[no ticket] updating contributor guide with jira reminder

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

- Add a variantstore cohort extract script
- Update the GATK custom built jar
AoU ticket: https://precisionmedicineinitiative.atlassian.net/browse/RW-5764

Update genomics tools on AoU image

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Bumping versions for https://github.com/DataBiosphere/terra-docker/pull/169

[no ticket] bump versions

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile
updateVersions.sc

https://broadworkbench.atlassian.net/browse/IA-2328
This PR updates the images for Bioconductor release 3.12.
- Should I be editing the changelog as well? They seem to be autogenerated.

[IA-2328] Update images to reflect Bioconductor 3.12 release

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile
updateVersions.sc

The versions match in terminal and in a notebook when tested locally.

[IA-2322] Remove miniconda to fix terminal

---

config/community_images.json

includes changes in the following two PRs:
https://github.com/anvilproject/anvil-docker/pull/23
https://github.com/DataBiosphere/leonardo/pull/1821

[IA-2460] change user installed R package dir

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

https://broadworkbench.atlassian.net/browse/IA-2511

[IA-2511] Attempt to fix Seurat installation

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

- Install gatk
- Install bolt-lmm
- Install regenie
- Install Nirvana (requires dot net)
- Install R packages: SAIGE, GENESIS
- Update Plink version

[RW-6313] Install additional AoU genomics tools

---

build.sh
jenkins/Jenkinsfile

210 was having issues and was brought offline.

[no ticket] Change to node 212

---

.gitignore
config/static_images.json

https://broadworkbench.atlassian.net/browse/IA-2731

IA-2731 remove legacy image

---

config/community_images.json

This is to capture work done in:
https://broadworkbench.atlassian.net/browse/IA-2767
https://broadworkbench.atlassian.net/browse/IA-2771

[IA-2767][IA-2771] Updating community image version

---

config/conf.json
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-hail/tests/hail_smoke_test.ipynb
updateVersions.sc

See https://broadworkbench.atlassian.net/browse/IA-2283
This seems to work locally; will also do a test in a real Spark environment in Terra

IA-2283: Add gnomad python package to Hail environment

---

.gitignore
terra-jupyter-base/Dockerfile
terra-jupyter-base/tests/smoke_test.py
terra-jupyter-bioconductor/tests/smoke_test.ipynb
terra-jupyter-python/tests/smoke_test.ipynb
terra-jupyter-r/Dockerfile

https://broadworkbench.atlassian.net/browse/IA-2686
* add `libgfortran5` dependency
* Add test for Seurat
I deleted published tags for `terra-jupyter-r`, `terra-jupyter-bioconductor`, `terra-jupyter-gatk`, `terra-jupyter-aou`, so I don't think need to bump versions

IA-2686 Fix Seurat install issue 

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-aou/tests/aou_smoke_test.ipynb
terra-jupyter-python/Dockerfile

See https://github.com/DataBiosphere/terra-docker/pull/209, we're changing base image to deep learning images...
AoU image had some issues, this PR is to bring AoU to base on [deep learning image](https://cloud.google.com/deep-learning-containers/docs/choosing-container) as well.

IA-2686 Upgrade AoU image to be based on deep learning base image

---

config/community_images.json
config/conf.json
scripts/utils.py

I tested the package generation locally. Also tested the image in Terra UI and it seems to work.

[IA-2929] Add OpenVINO as a community image

---

README.md

https://broadworkbench.atlassian.net/browse/IA-2928
cc  @ac3eb

IA-2928 add more instructions around building custom images

---

config/community_images.json

integrating this PR with leo: https://github.com/anvilproject/anvil-docker/pull/33

[IA-2981] bump rstudio version to 3.13.3

---

config/community_images.json

integrating this [PR](https://github.com/anvilproject/anvil-docker/pull/35) with leo

IA-3052 bump rstudio to 3.14

---

.github/workflows/test-terra-jupyter-aou.yml
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

User does not have permission on user/bin/
Then I followed above example (plink) and put it in a new dir. 
I followed the tutorial here: https://github.com/DataBiosphere/terra-docker#testing-your-image-manually
But it is still accessing terminal as root. Not sure if that will work in the real case, but based on plink example, the new way should work.

[RW-7392]Move nextflow into a right location

---

.github/workflows/test-terra-jupyter-gatk-ovtf.yml
.github/workflows/test-terra-jupyter-gatk.yml
config/community_images.json
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile

Upgrading GATK to latest. Will see how the smoke tests do here.

[IA-3138] Upgrade GATK to 4.2.4.0

---

config/community_images.json

Updating the UI for the new OVTF image from this PR: https://github.com/DataBiosphere/terra-docker/pull/279

[IA-3192] Updating OVTF Community Image

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Removed Nextflow installation from AoU image and put it into the GATK image
Tested by building and running a container locally and going through the Nextflow tutorial (https://www.nextflow.io/docs/latest/getstarted.html) to verify that Nextflow runs as expected. Saw Nextflow Hello World work correctly.

[IA-3327] Added Nextflow to GATK

---

config/community_images.json

Edit the config file for latest RStudio changes.

Update version number of RStudio in the config file

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Reverts DataBiosphere/terra-docker#328

Revert "[IA-3261] Added chown command for /opt/conda."

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

The change that I need: https://github.com/broadinstitute/cromwhelm/pull/34

[RW-8461] Bump base image and all sub images to fix leo_url in cromwell python script

---

config/conf.json
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile

AnVIL package will install with this fixed link - requested by Alassandro
- Requires rebuild of the image and other changes to README files and version number changes.

[SUP-496] Fix link to make sure AnVIL package installs

---

config/community_images.json

Friends with https://github.com/anvilproject/anvil-docker/pull/46

Update community_images.json for RStudio version

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Reopening of https://github.com/DataBiosphere/terra-docker/pull/373 from branch per Qi's request.
Friends with https://github.com/DataBiosphere/terra-docker/pull/372

IA-3868 Change Bioconductor version for Jupyter

---

.github/workflows/test-terra-jupyter-aou.yml
.github/workflows/test-terra-jupyter-base.yml
.github/workflows/test-terra-jupyter-bioconductor.yml
.github/workflows/test-terra-jupyter-gatk-ovtf.yml
.github/workflows/test-terra-jupyter-gatk.yml
.github/workflows/test-terra-jupyter-hail.yml
.github/workflows/test-terra-jupyter-python.yml
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-python/requirements.txt
terra-jupyter-python/tests/smoke_test.py
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

For reviewers:
There are a lot of files changed, but they can be easily categorized.
The .yml file changes are all updating the authentication key for Github actions.
The Dockerfiles (Other than terra-jupyter-base) have spacing changes.
And smoke_test.py had a test removed for the time being. Follow up ticket: https://broadworkbench.atlassian.net/browse/IA-4061

[IA-4036] Updated base dockerfile and appropriate documents.

---

.github/workflows/pull_request_template.md

- Add a PR template to the repository.
- Gives better guidance when suggesting code changes.

[IA-4263] Added basic PR template.

---

config/community_images.json

- Updates R to 4.3.1 (xref https://github.com/Bioconductor/AnVIL/issues/89)

Update BiocRstudio version and rename to main

---

.github/workflows/test-terra-jupyter-aou.yml
.github/workflows/test-terra-jupyter-bioconductor.yml
.github/workflows/test-terra-jupyter-gatk.yml
.github/workflows/test-terra-jupyter-hail.yml
.github/workflows/test-terra-jupyter-python.yml
build_smoke_test_image.sh
config/conf.json
terra-jupyter-bioconductor/tests/smoke_test.ipynb
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/tests/smoke_test.ipynb

https://broadworkbench.atlassian.net/browse/IA-5008
Depends on Dataproc upgrade: https://github.com/DataBiosphere/leonardo/pull/4699

[IA-5008] Update Hail to 0.2.131

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile

JIRA ticket: https://broadworkbench.atlassian.net/browse/IA-5041

[IA-5041] Update both hail and aou images to use hail version 0.2.130.post1

---

config/legacy_static_images.json

Change legacy to the 3.19 container

Update BiocJupyter legacy to 3.19

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile

JIRA Ticket: https://broadworkbench.atlassian.net/browse/AN-503

[AN-503] Update hail to 0.2.134
