DataBiosphere/terra-docker

terra-jupyter-python/Dockerfile

Remove apt cache to reduce size of image.
The removal of cache reduces the image size by 240MB.
```
terra-jupyter-python:v2     5GB
terra-jupyter-python:v1     5.24GB
```
where, v1 is the original docker image, and v2 includes the removal of
the cache.

Remove cache tjp

---

build.sh
hub/Dockerfile
jenkins/Jenkinsfile
jenkins/imageDirs.txt

- Update build script to be able to correctly source the vault token regardless of if it is run on jenkins or local (this is redundant, as the jenkins job gets the token, but I'd rather have redundant defensive code than auth errors)
- Fix issue where the job does not properly order image builds
- Job will now fail appropriately when an image fails to build
- Disable doc generation for gatk until pip is working
- Job will now create PRs
- Dockerimage for hub, the tool used to create PRs via CLI, is added

[IA-1417] Jc update jenkinsfile

---

config/conf.json
terra-jupyter-hail/Dockerfile

https://broadworkbench.atlassian.net/browse/IA-1237
`hl.spark_context()` returns `yarn` properly now.
I tried the hl.balding_nichols_model(3, 100000, 10000)._force_count_rows() and I can see cpu spikes in workers clearly every time I run this, and it finishes a lot faster than previously. And I see logs like
```
DIR* completeFile: /yarn-logs/jupyter-user/logs/application_1574015922767_0002/saturn-3bdc666f-4a63-4265-b3fe-c769598f9f7a-w-0.c.qi-billing.internal_32843.tmp is closed by DFSClient_NONMAPREDUCE_-1710167753_128
```
in hadoop log (assuming this is indication that hadoops is running some job from jupyter)...

IA-1237 update hail dockerfile

---

config/conf.json
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

1. r-base: this installs the r-recommended packages since it's a
dependency and these packages get installed in "/usr/lib/R/library".
2. r-recommended: this basically does the same thing as installing the
packages in the /usr/lib/R/library location.
We want to avoid installing the r-recommended packages, so both r-base
and r-recommended are removed. To allow installation to happen for these
recommended packages in /home/jupyter-user/.rpackages, they are
individually listed in the BiocManager::install command.
The "ask" option is added as FALSE to the BiocManager, as we don't want
to update unprompted. See below,
ask: 'logical(1)' indicating whether to prompt user before
installed packages are updated.  If TRUE, user can choose
whether to update all outdated packages without further …

Avoid r-recommended packages being installed in /usr/lib/R/library 

---

config/conf.json
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile

Corrects an issue seen in All of Us for the terra-jupyter-gatk:0.0.3 image (also present in 0.0.4) when installing packages which depend on `-lgfortran` such as `questionr`.
Before:
After:

bump terra-jupyter-gatk to 0.0.5 - includes terra-jupyter-r:0.0.6

---

config/conf.json
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

This PR will update the version of Bioconductor to the latest release 3.10.

Update Bioconductor to version 3.10

---

config/conf.json

One theory about why AOU cluster startup increased since 11/19 is that they started to use terra-jupyter-gatk image, and we saw huge increased startup time since then in perf (altho it doesn't seem to affected prod much)

include gatk image in custom dataproc image

---

terra-jupyter-python/Dockerfile

tested in https://github.com/DataBiosphere/leonardo/pull/1189

fix ggplot

---

build.sh
jenkins/Jenkinsfile

**The job will still be broken the next run after this, but should work on subsequent runs since the cleanWs() function is called as a post-action (which is its recommended usage)**
- adds back docker auth for case when no images are built but docs do a no-op upload
- cleans the workspace after the run
- removes manual cleaning of a file
- build script works locally again

[IA-1561] Jc clean workspace

---

README.md
config/conf.json
scripts/generate_version_docs.py
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-base/README.md
terra-jupyter-base/jupyter_notebook_config.py
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Not fully tested yet. This resolves a few tickets:
1. https://broadworkbench.atlassian.net/browse/IA-1602 (make docker images runnable locally)
2. https://broadworkbench.atlassian.net/browse/IA-1617 (install FISS in base image)
3. https://broadworkbench.atlassian.net/browse/IA-1624 (gatk label should be all caps)
4. https://broadworkbench.atlassian.net/browse/IA-1629 (add openjdk to the base image)
Also, while I'm updating the base, let me know if there are other updates we should make!

IA-1602 IA-1617  IA-1624 IA-1629 Make terra-docker images runnable locally

---

config/conf.json
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-hail/scripts/kernel/kernelspec.sh
terra-jupyter-hail/scripts/kernel/python_kernelspec.tmpl

The main fix is to specify the `PYSPARK_PYTHON=python3` env variable in the kernel definition. Otherwise it seems to default to python 2.7. See: https://cloud.google.com/dataproc/docs/tutorials/python-configuration

[IA-1637] Hail jobs fail with "mismatched python version"

---

build.sh

- prevents IMAGE_EXISTS being triggered on VERSIONS containing a substring of the VERSION we care about
- changes from pipe to or to avoid termination on failed commands, which was messing up line 15

Jc fix build

---

config/conf.json
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile

See https://broadworkbench.atlassian.net/browse/IA-1706
We currently install Java 11. Apparently GATK requires exactly Java 8:
https://gatk.broadinstitute.org/hc/en-us/articles/360035889531
> Java 8 / JRE or SDK 1.8
> The GATK is a Java-based program, so you'll need to have Java installed on your machine. The Java runtime version should be at 1.8 exactly. To be clear: we do not yet support 1.9, and older versions (1.6 and 1.7) no longer work. You can check what version you have by typing java -version at the command line. This article has some more details about what to do if you don't have the right version. Both the Sun/Oracle Java JDK and OpenJDK versions are fully supported.

[IA-1706] Install JDK 8 in the gatk image

---

README.md
config/conf.json
scripts/generate_package_docs.py
scripts/generate_version_docs.py

- doc scripts updated to have docs include requiresSpark
- hail doc updated to include spark version
I chose to refactor the usage of 'tools' so that 'spark' is actually a valid tool instead of duplicating spark as a flag in `conf.json`
I've uploaded the new hail doc with the spark version, but I haven't renamed the `..versions-new.json` file that terra reads from yet (aka hail docs in UI are live with spark version, but requireSpark flag isn't included yet).
After merge I will need to rename the `-new.json` file for this to take effect.

[IA-1805] add requiresSpark flag to UI-facing documentation

---

config/conf.json
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile
terra-jupyter-r/README.md

- Create new entry in CHANGELOG file.
- This image will include most of CRAN and Bioconductor system dependencies.
- Makes the notebook actually useable by analysts.
- Remove Bioconductor packages
- Add environment variables R_PLATFORM and R_PLATFORM_BINARY_VERSION, these are needed to make the binary package installation of R packages.

terra-jupyter-r:0.0.12

---

config/conf.json
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

This PR fixes the bug where env variables WORKSPACE_BUCKET and
WORKSPACE_NAME are not found.
Alters the names R_PLATFORM to TERRA_R_PLATFORM so that there is no
conflict between base R installation.

Fix env variables name and bug fix

---

config/conf.json
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile

Google bucket support of pysam is not enabled by default in the PyPI package. It would be great to enable it explicitly in the docker file.

IA-1856 Compile pysam explicitly with google cloud support

---

config/conf.json
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile

All images need to launch as `jupyter-user`, not as `root`. Will run Leo automation tests against this.

Fix bug in bioconductor image

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

- Update terra-jupyter-r to include the latest release version of R,
R-4.0.0
- terra-jupyter-r also updates the Bioconductor version to release 3.11.
- The terra-jupyter-bioconductor and terra-jupyter-aou images are
updated as a consequence of the updates to the terra-jupyter-r images.
- Updates to CHANGELOG.md in all the files.

Update to R-4.0.0

---

config/conf.json
scripts/generate_version_docs.py

Made labelling changes based on https://docs.google.com/document/d/1qAp1wJTEx1UNtZ4vz1aV4PZRfjyYfF7QkwwOjK4LoD8/edit
Manually ran `generate_version_docs.py` and pushed result to `gs://terra-docker-image-documentation/terra-docker-versions-new.json`. It looks correct to me -- we can push to Terra UI whenever we are ready (probably next Leo release).
```
$ gsutil cat gs://terra-docker-image-documentation/terra-docker-versions-new.json
[
{
"updated": "2020-05-21", 
"image": "us.gcr.io/broad-dsp-gcr-public/terra-jupyter-bioconductor:1.0.0", 
"label": "R / Bioconductor: (Python 3.7.7, R 4.0.0, BiocVersion 3.11.1, tidyverse 1.3.0)", 
"version": "1.0.0", 
"requiresSpark": false, 
"packages": "https://storage.googleapis.com/terra-docker-image-documentation/terra-jupyter-bioconductor-1.0.0-versions …
```

IA-1915 Legacy R images and new labels

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

jupyter r image now installs image packages as root user and then creates directory `/home/jupyter-user/notebooks/packages` and uses that for user installed packages. 
removes directory `/home/jupyter-user/.rpackages` so `.libPaths()` doesn't have too many entries (we will be using new dir going forward since it's the same dir we mount the persistent disk on)
this PR also changes ownership of `/usr/local/lib/R/site-library` to `jupyter-user` as requested by @nturaga

IA-1973 - Update jupyter R image so user installed packages persist

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

This PR removes `/home/jupyter-user/notebooks/packages` from `.Renviron` in `terra-jupyter-r` so that derived images such as `terra-jupyter-bioconductor` package installations don't persist

IA-1973 Persist only user installed packages

---

terra-jupyter-hail/README.md

2 people have commented on this in 1 day. I didn't realize we still had this text in the README.

[no ticket] Remove outdated disclaimer from terra-jupyter-hail readme

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

- Drop fork install of bigrquery (patches have now been merged and released in the main bigrquery package)
- Install new AoU Python library
- Bump aou image tag to 0.0.4
Tested via building locally and executing Python and R shells within the docker container.

Update workbench-snippets and bigrquery AoU libraries

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

plotnine 0.7.0 requires pandas 1.0, which I think will have other side-effects. Will investigate upgrading this separately.

Fix pandas version on AoU docker image

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Tested by building a custom image, pushing it, and installing a pip package with cli functionality. (`janis-pipelines` to be specific).
Worth noting that I couldn't test this locally with an image because of the directory setup our init script does... may be worth touching up a terra-docker script that sets up the pathing as the init script does.

[IA-2076] fix issue with path and update all images

---

terra-jupyter-python/Dockerfile

https://broadworkbench.atlassian.net/browse/IA-2040
We install notebook in base. it shouldn't be needed in python image.
I'll delete the `us.gcr.io/broad-dsp-gcr-public/terra-jupyter-python:0.0.15` from gcr, hence not bumping version

IA-2040 remove explicit notebook install from python image

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Add line to `/home/jupyter-user/.bashrc` that defaults the user's terminal to the directory where the PD is mounted.
Tested all of the following images (built them with my test base image with the new change): `terra-jupyter-base`, `terra-jupyter-python`, `terra-jupyter-aou` and verified that when I opened Jupyter then clicked New --> Terminal that the default directory is the correct one:
I also verified that everything pip that the images install is in the same directory as before (installed as root user and for the aou image some are installed as `jupyter-user` so I made sure those are where they're supposed to be as well)

[IA-2169] Terminal default directory is now where PD is mounted

---

build.sh

this check is timing out and causing the image build job to fail. cc @zbedo  , I'm fairly sure you're aware already

[No ticket] comment out problematic security check for now

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

AoU ticket: https://precisionmedicineinitiative.atlassian.net/browse/RW-5412
- Add Hail to AoU image
- Bump GATK branch commit
Verified that Hail is functional with Dataproc, and pyspark fails to import on GCE, which is reasonable behavior for now.
CC @ahaessly @petesantos @ericsong @rtitle @als364

AoU image: add Hail dependencies

---

config/conf.json
terra-jupyter-hail/CHANGELOG.md

Making a dummy 0.0.22 hail version because I think 0.0.21 was skipped due to CI/CD issues.

Bump hail to 0.0.22 to force a rebuild. No changes to the image since 0.0.21.

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile
updateVersions.sc

This should allow Terra terminal users to execute pip installed binaries without manually modifying PATH.
It is also useful for automated CI/CD testing of notebook code in Leo environments, e.g. https://github.com/DataBiosphere/bdcat_notebooks

Include pip binary installation location in PATH

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

Invoking gsutil from the Docker build process has side-effects: avoid.
As an end user, this resulted in errors such as:
```
!gsutil ls ${WORKSPACE_BUCKET}
Traceback (most recent call last):
File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/util/files.py", line 1227, in _FileOpener
return io.open(path, mode, encoding=encoding)
PermissionError: [Errno 13] Permission denied: '/home/jupyter-user/.config/gcloud/active_config'
```

Don't use gsutil in the aou Dockerfile, causes CLI issues

---

terra-jupyter-base/Dockerfile

Add package 'keychain' to base image to facilitate use of 'ssh-agent' and 'ssh-add'.

---

config/community_images.json
config/static_images.json
scripts/generate_version_docs.py

Tested by doing the following:
- ran the `generate_version_docs.py` script, replacing `terra-docker-versions-new.json` with `gabriela-test-rstudio.json` and verified that the json file that gets generated is what we expect it to be, the only difference being that the new file includes the RStudio image.
- The corresponding terra-ui changes can be found in this PR: https://github.com/DataBiosphere/terra-ui/pull/2291
- Tested that I could create a runtime using the new rstudio image on my local terra-ui branch (by using the `gabriela-test-rstudio.json` file that i pushed to the google bucket) and everything is working as expected
Screenshot of terra-ui changes:

[IA-2255] Add RStudio/Bioconductor image to cloud environments dropdown

---

config/community_images.json

See: 
https://broadworkbench.atlassian.net/browse/IA-2235
https://github.com/anvilproject/anvil-docker/pull/20
https://github.com/DataBiosphere/leonardo/pull/1674
I'm also bumping it in Leo automation tests and generating new custom GCE/Dataproc images. My plan is to make this live next week after the next Leo release.
@gpcarr how do I generate a new `terra-docker-versions-new.json` after merging this?

[IA-2235] Bump RStudio version

---

config/community_images.json

https://broadworkbench.atlassian.net/browse/IA-2345
anvil-docker PR: https://github.com/anvilproject/anvil-docker/pull/21
Leo PR: https://github.com/DataBiosphere/leonardo/pull/1692

IA-2345: Update anvil-rstudio-bioconductor to 0.0.8

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
updateVersions.sc

Merged from https://github.com/DataBiosphere/terra-docker/issues/175, also updates versions.
JIRA to track: https://broadworkbench.atlassian.net/browse/IA-2346

IA-2346 terra-docker: Remove Python package enum34

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile
updateVersions.sc

going to be closing this PR: https://github.com/DataBiosphere/terra-docker/pull/184
changes to `updateVersions.sc` were tested using both `amm ./updateVersions.sc terra-jupyter-base "[message]"` and `amm ./updateVersions.sc terra-jupyter-r "[message]"`

Move terra-notebook-utils to base image and bump all image versions

---

terra-jupyter-base/Dockerfile
terra-jupyter-python/Dockerfile
terra-jupyter-r/Dockerfile

This PR fixes the base image by adding `pip3 install six==1.15.0` and installing `python3.7-dev` instead of `python3.7` and moving `pip3 install terra-notebook-utils==0.7.0` to after we install `firecloud` because TNU depends on firecloud
Removes `six` and `python3.7-dev` installation from python and r images since now we install them in base image

Fix base image

---

terra-jupyter-python/Dockerfile

Newer versions of this library no longer depend on the obsolete enum34 library.
Fixes https://github.com/DataBiosphere/terra-docker/issues/175

Update to a newer version of pymc3.

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md

Original PR with the actual change: https://github.com/DataBiosphere/terra-docker/pull/188
This PR bumps the versions of python, hail, gatk, and aou images.

[IA-2420] Update to a newer version of pymc3

---

terra-jupyter-base/jupyter_notebook_config.py

(Note: see https://github.com/DataBiosphere/leonardo/pull/1833 for related Leo PR keeping both files in sync.)
Turns on conditional debug-level logging for the Jupyter application, controlled by an environment variable.

[IA-2472] Turn on debug-level logging when JUPYTER_DEBUG_LOGGING env var is true

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Ran:
```
amm ./updateVersions.sc terra-jupyter-base "[IA-2472] Turn on debug-level logging when JUPYTER_DEBUG_LOGGING env var is true"
```
Original PR: https://github.com/DataBiosphere/terra-docker/pull/193
[IA-2472]: https://broadworkbench.atlassian.net/browse/IA-2472

Bump versions for IA-2472

---

.github/workflows/trivy.yml
build.sh
terra-jupyter-base/Dockerfile

This change adds Trivy security scan for the Docker image, as discussed in the Workbench Cross-Team meeting.
The action will run on every PR and give you feedback if the Docker image contains critical OS vulnerabilities.
More info:
https://github.com/broadinstitute/dsp-appsec-trivy-action
https://github.com/broadinstitute/dsp-appsec-blessed-images

[IA-2343] Add AppSec Github Trivy Action

---

terra-jupyter-python/Dockerfile
terra-jupyter-r/Dockerfile

I think this was causing issues starting up Jupyter in the latest terra-docker build. Example error from AoU image (which extends from both python and r images):
```
$ docker run --rm -it -p 8000:8000 us.gcr.io/broad-dsp-gcr-public/terra-jupyter-aou:1.0.21
[I 00:49:37.496 NotebookApp] initializing DelocalizingContentsManager
[I 00:49:37.503 NotebookApp] Writing notebook server cookie secret to /home/jupyter-user/.local/share/jupyter/runtime/notebook_cookie_secret
[W 00:49:37.731 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[W 00:49:37.751 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/notebook/notebookapp.py", line …
```

[no ticket] Update pyyaml versions to be consistent across python and r images

---

config/conf.json
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile

This PR updates `terra-jupyter-hail` to use hail version 0.2.62. 
@Qi77Qi  asked if we could update hail to depend on a newer version of pandas. Hail version 0.2.62 makes this change, allowing pandas versions: pandas>=1.1.0,<1.1.5

Update hail to 0.2.62

---

.github/workflows/test-terra-jupyter-aou.yml
.github/workflows/test-terra-jupyter-gatk.yml
.github/workflows/test-terra-jupyter-hail.yml
.github/workflows/test-terra-jupyter-python.yml
terra-jupyter-gatk/tests/gatk_smoke_test.ipynb
terra-jupyter-hail/tests/hail_smoke_test.ipynb

Add smoke test workflows for the GATK and Hail images which also depend on `terra-jupyter-python`. (A subsequent PR will modify the Dockerfile for terra-jupyter-python and add more test coverage.) 
Please see these successful runs of these new workflows:
* https://github.com/deflaux/terra-docker/actions/runs/612153437
* https://github.com/deflaux/terra-docker/actions/runs/612153436

Add more smoke tests.

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-python/tests/smoke_test.ipynb
terra-jupyter-python/tests/smoke_test.py

Also:
* added package `plotnine` per #126
* replaced package `tensorflow` with `tensorflow_cpu` to get rid of the warnings about GPUs being unavailable for Terra Cloud Runtimes
* added package `google-resumable-media` as an explicit dependency to ensure a more recent version of it is used, pandas-gbq depends on it for table uploads
* `--use_rest_api` flag is now needed for `%%bigquery magic`
* As of release [google-cloud-bigquery 1.26.0 (2020-07-20)](https://github.com/googleapis/python-bigquery/blob/master/CHANGELOG.md#1260-2020-07-20) the BigQuery Python client uses the BigQuery Storage client by default.
* This currently causes an error on Terra Cloud Runtimes `the user does not have 'bigquery.readsessions.create' permission for '<Terra billing project id>'`.
* To work-around this we …

Update all Python package versions by unpinning them.

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-python/tests/smoke_test.ipynb

when running `from ggplot import *` we get the following error:
`AttributeError: module 'pandas' has no attribute 'tslib'`
Adding the last three `sed` commands in this PR fixes this error but we then still get error:
`ModuleNotFoundError: No module named 'pandas.lib'`
adding the first `sed` command fixes this second error.
This error was caught by automation tests: https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/34649/testReport/junit/org.broadinstitute.dsde.workbench.leonardo.notebooks/NotebookPyKernelSpec/NotebookPyKernelSpec_should_be_able_to_import_ggplot_for_Python3/
These `sed` commands were present before these [PR](https://github.com/DataBiosphere/terra-docker/pull/207) changes so this PR just adds them back
Tested that running `from ggplot import …

[IA-2638] add fix back in to fix ggplot import bug

---

config/community_images.json

The parent image bioconductor/bioconductor_docker:RELEASE_3_12 included critical bug fixes.
The new image is located in us.gcr.io/anvil-gcr-public/anvil-rstudio-bioconductor:0.0.11

Update anvil-rstudio-bioconductor image to 0.0.11

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-python/tests/smoke_test.ipynb
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

JIRA: https://broadworkbench.atlassian.net/browse/IA-1644
Details about composite objects: https://cloud.google.com/storage/docs/composite-objects
The new test failed before the fix: https://github.com/DataBiosphere/terra-docker/runs/2511051906?check_suite_focus=true
...and passed after the fix 🎉 : https://github.com/DataBiosphere/terra-docker/runs/2511404254?check_suite_focus=true
To get things to work I had to fix a couple unrelated things, noted inline in the comments.
@mikebaumann fyi

[IA-1644] Install crcmod in base image to support GCS composite objects

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

This change is somewhat redundant, but this is the second time terra-widgets dependencies have caused issues with the build for terra-jupyter-aou.
The root cause of the test failures in https://github.com/DataBiosphere/terra-docker/pull/217 will be fixed by https://github.com/all-of-us/workbench-snippets/pull/65

Reduce unnecessary package upgrades.

---

config/conf.json
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

- Update R to 4.1.0 (latest stable release)
- Update Bioconductor to 3.13 (latest stable release)
- Add a library needed for installing a Bioconductor package (RCy3) -- libzmq3-dev
General changes:
- Update CHANGELOG.md (this seems to be an auto-update, not sure I needed to do it)
- Update config.

Updates to jupyter-r image to R 4.1.0 and Bioconductor 3.13

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile

Bumps dependent images with this `terra-jupyter-r` change: https://github.com/DataBiosphere/terra-docker/pull/221
https://broadworkbench.atlassian.net/browse/IA-2810

IA-2810 Update Jupyter image stack to Bioconductor 3.13.0

---

config/community_images.json

See https://github.com/anvilproject/anvil-docker/pull/32 and https://broadworkbench.atlassian.net/browse/SUP-503
This image is already pushed to GCR and tested in Terra.

[SUP-503] Update Rstudio version for ggplot2 fix

---

.github/workflows/test-terra-jupyter-aou.yml
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-aou/gitignore_global
terra-jupyter-aou/tests/aou_smoke_test.ipynb

Also
* re-enable the tests
* add tests for the source control protections
* `apt-get install less` to make looking through large hail logs easier
* `pip3 install papermill` to facilitate parameterized Hail notebooks run in the background, see also https://github.com/DataBiosphere/terra-example-notebooks/pull/21

Add global gitignore to terra-jupyter-aou

---

config/static_images.json

Remove legacy gatk image because it is over a year outdated. @gpcarr will take care of CI and generating new json file.

[IA-2827] remove legacy gatk img

---

config/community_images.json

* Use `pegasus` v1.4.3.
* Image based on `us.gcr.io/broad-dsp-gcr-public/terra-jupyter-base:1.0.0`.
* Update dependency Python packages.

Update Pegasus image to v1.4.3

---

config/legacy_static_images.json
scripts/generate_version_docs.py

tested with minor and major version bumps of both GATK and Bioconductor images and validated that when we use the current image as the new legacy image, the label gets changed to reflect that it is now a legacy image

[IA-2897] Change label for legacy images

---

terra-jupyter-gatk-ovtf/README.md
terra-jupyter-gatk-ovtf/tests/ovtf_smoke_test.ipynb
terra-jupyter-gatk-ovtf/tests/ovtf_smoke_test.py

@rtitle We added simple tests for verifying OVTF.
Once the CI/CD pipe line is working, we need to update the `README` to update the container path to `us.gcr.io/broad-dsp-gcr-public/....`
cc: @cavusmustafa

Adding Simple tests for OVTF

---

config/community_images.json
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-python/tests/smoke_test.ipynb
terra-jupyter-python/tests/smoke_test.py
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

See: 
* https://broadworkbench.atlassian.net/browse/IA-2902
* https://github.com/DataBiosphere/terra-docker/issues/244
This PR updates the `terra-jupyter-base` parent image to `gcr.io/deeplearning-platform-release/tf2-gpu.2-6 `. This supports tensorflow 2.6.0 with GPUs, whereas previously only 2.4.0 was supported due to a CUDA library mismatch.
The base image size difference is:
* old: 13.5GB
* new: 16GB
Since we cache all the images I think the size differential is reasonable.
Added a couple test cases around tensorflow which should run on this PR. I'll also do some local manual testing.
Note: this PR also includes https://broadworkbench.atlassian.net/browse/IA-2956
After this PR is merged and the images are built and pushed, we will rebuild the Leo custom image (to update the caches), …

[IA-2902] [IA-2956] Use tf2-gpu.2-6 as base image

---

config/conf.json
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile

I made the normal changes that I make when updating hail version in Terra, but it's worth noting that Hail has also updated from using Spark 2.4.x to Spark 3.1.x by default. Are there other changes I have to make to reflect this?

Update hail to 0.2.74

---

config/community_images.json

Simple fix of version number in R from 4.1.0 to 4.1.2

Update community_images.json to fix R version number

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

The intended change with https://github.com/DataBiosphere/terra-docker/pull/263/files#diff-df40bbb7ec38ec9c9fcdba2e7f8375b32309e761e675b54d5182f63b023b23b0R1 was to bump to 2.0.4. This was an easy error since aou and gatk were confusingly close in version numbers.

Switch AoU to latest gatk base

---

.github/workflows/test-terra-jupyter-bioconductor.yml
.github/workflows/test-terra-jupyter-hail.yml
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-bioconductor/tests/smoke_test.ipynb
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile
terra-jupyter-r/README.md

Update Terra Jupyter image to use latest Bioconductor 3.14.
https://broadworkbench.atlassian.net/browse/IA-3143

IA-3143 Update terra-jupyter-r image to Bioc 3.14, R 4.1.2

---

.github/workflows/test-terra-jupyter-python.yml
terra-jupyter-base/Dockerfile
terra-jupyter-python/Dockerfile
terra-jupyter-python/tests/smoke_test.ipynb

Added new tests to demonstrate:
1) that new Python packages can be installed via pip <-- works
2) that new Python packages **_compiled from source_** can be installed via pip <--- won't work till after https://github.com/DataBiosphere/terra-docker/issues/285 is fixed, the final assertion is commented out for now
Also fixes some test breakage:
* address tensorflow 2.6 test failures by
* pinning the package version of Keras
* ensuring that the installation of pytest does not upgrade pyparsing
* fix test auth failures by updating to the latest gcloud github actions

Add pip install tests to terra-jupyter-python.

---

CONTRIBUTING.md
config/legacy_static_images.json
scripts/generate_version_docs.py

This PR adds a few things around legacy images:
- Adds documentation in CONTRIBUTING.md on how terra-docker legacy image versioning works
- hard codes the legacy bioconductor image as 2.0.2 until the next bioconductor release (we have to do this because when we bumped to bioc 3.14, we only did a patch version bump of the bioc image instead of a minor version bump)
- removes a TODO for computing legacy images

[IA-3156] legacy image changes

---

scripts/generate_version_docs.py

when we need to compute a new legacy image, we should replace its `id` to reflect that it is a legacy image

[IA-3156] fix id for legacy images

---

config/conf.json
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk-ovtf/README.md
terra-jupyter-gatk-ovtf/ovtf-cuda-disabling.patch

Hi @Qi77Qi, @rtitle 
OVTF1.1.0 is released, we updated the dockerfile.
- Along with the OVTF update, we updated with GATK-4.2.4.1, TF-2.7.0.
- GPU support is enabled. We added notes on GPU support in the README.
- The end-user options are either:  `OVTF with CPUs` or `Native TF with CPUs/GPUs`
CC: @cavusmustafa

Update to OVTF1.1.0, GATK4.2.4.1, TF2.7.0

---

terra-jupyter-python/Dockerfile
terra-jupyter-python/tests/smoke_test.ipynb

Added the following Intel classical ML Python optimizations and  installs to existing terra-jupyter-python Docker image:
- Intel Distribution of Modin
- Intel Extension for Scikit-Learn
- Intel optimizations for XGBoost
- Intel optimized NumPy, SciPy, and Numba (message me for details)
Added validation tests to smoke_test.ipynb for the following:
- Intel Distribution of Modin
- Intel Extension for Scikit-Learn
- Intel optimizations for XGBoost

Add Intel classical ML optimization install and tests to terra-jupyter-python Docker image

---

.github/workflows/test-terra-jupyter-python.yml
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-base/jupyter_notebook_config.py
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

https://broadworkbench.atlassian.net/browse/IA-2965
For images derived from terra-jupyter-python, the change log also includes https://github.com/DataBiosphere/terra-docker/pull/278, because that PR didn't have version bump and there was no new images generated

IA-2965  Update after PD mount change

---

config/community_images.json

Includes changes in this PR: https://github.com/anvilproject/anvil-docker/pull/37

[IA-2991] update Rstudio to 3.14.1

---

config/community_images.json

This will update the anvil-rstudio-bioconductor docker image that was rebuilt.
- this will add additional sys dependencies to make more Bioconductor packages work.
Related PR https://github.com/anvilproject/anvil-docker/pull/41

Update anvil-rstudio-bioconductor image

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

We were seeing an issue with the scipy package given the previous Hail installation interactions. I'm not totally clear on why this manifested as it did, but it looks like some bad interaction with the Hail install instructions that uninstall several packages.
```
docker run -t --entrypoint='' --rm us.gcr.io/broad-dsp-gcr-public/terra-jupyter-aou:2.0.12 pip install scipy
Requirement already satisfied: scipy in /opt/conda/lib/python3.7/site-packages (1.7.3)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/scipy-1.7.3.dist-info/METADATA'
```
Upgrading to the latest Hail install pattern resolves this.

AoU: update base image, bump Hail

---

config/community_images.json

Update the config file to reflect changes in the anvil-rstudio-bioconductor image. Updates to Bioconductor version 3.15 and R 4.2.0.
Based on bioconductor/bioconductor_docker:RELEASE_3_15

Update RStudio image to Bioc 3.15.0 and R 4.2.0

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

To test if cromshell was installed properly, I added the `cromshell-alpha --help` command to the dockerfile and this was the result from test run (it has now been removed):
```
Step 18/29 : RUN git clone https://github.com/broadinstitute/cromshell.git  && cd cromshell  && git checkout cromshell_2.0  && pip install .  && cromshell-alpha --help
---> Running in 3447216c2a39
Cloning into 'cromshell'...
Switched to a new branch 'cromshell_2.0'
Branch 'cromshell_2.0' set up to track remote branch 'cromshell_2.0' from 'origin'.
....
....
Successfully built cromshell
Installing collected packages: pygments, cromshell
Attempting uninstall: pygments
Found existing installation: Pygments 2.11.2
Uninstalling Pygments-2.11.2:
Successfully uninstalled Pygments-2.11.2
Successfully installed …
```

BW-1234 Install cromshell 2.0 to terra-jupyter-base image

---

build_smoke_test_image.sh
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

I tested it by building it locally and it `workspace-cromwell.py` was available in the image. Using it caused error because the env variables were not set.
```
terra-jupyter-base % docker run --rm -it -u root -p 8000:8000 --entrypoint /bin/bash sshah-terra-juypter-base
root@31b75eb2f247:~# ls
workspace_cromwell.py
root@31b75eb2f247:~# python3 workspace_cromwell.py start
Traceback (most recent call last):
File "workspace_cromwell.py", line 296, in <module>
main()
File "workspace_cromwell.py", line 260, in main
'workspace_namespace': os.environ['WORKSPACE_NAMESPACE'],
File "/opt/conda/lib/python3.7/os.py", line 681, in __getitem__
raise KeyError(key) from None
KeyError: 'WORKSPACE_NAMESPACE'
```
Closes https://broadworkbench.atlassian.net/browse/BW-1235

BW-1235 Add workspace-cromwell.py script to terra-jupyter-base image

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

For testing, I ran [leonardo-build-terra-docker #3837](https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-build-terra-docker/3837/console) to build only the base image and used it to create a custom notebook environment. The script is available in `/usr/local/bin` folder. 
(I had started the app in notebook terminal hence it is already in running state)
Submitting workflow through cromshell
The workflow eventually succeeded. Deleting the app:
Closes https://broadworkbench.atlassian.net/browse/BW-1235

BW-1235 Fixes `workspace_cromwell.py` not available in notebook

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

User runs conda install <package> and gets permissions error.
The conda installation and associated packages are owned by root:root, so when the "jupyter" user goes to install they will not have permissions to make changes.
Enable users to have greater control over Conda installs by changing ownership of /opt/conda
Also update to newer version of conda by upgrading the deeplearning base image.

[IA-3261] Added chown command for /opt/conda.

---

CONTRIBUTING.md

Added some new best practices with the terra-docker-versions.json. So added a line in the contributing guide to mention that.

[IA-3042] update contributing guide

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-python/requirements.txt

See https://broadworkbench.atlassian.net/jira/software/c/projects/IA/issues/IA-3401 for a description of the bug.
I narrowed the cause down to the GATK image (the issue did not repro in -base, -r, -python). I then further narrowed it down to the way in which sites-packages were being copied from the python image. I'm not 100% sure of why the previous approach caused this bug, but my suspicion is that bringing packages through the backdoor like this missed some initialization or setup with the base conda environment; the bug seems related to installing with conda vs pip.
By switching to a requirements.txt file in terra-jupyter-python, we can reuse the dependencies in both images via `pip install -r`.
This also:
- removes the setuptools downgrade in the python image, pysam now installs, so …

[IA-3401] Fix broken Python packages in gatk / AoU images

---

terra-jupyter-aou/Dockerfile

2.0.0 was just released, and causes issues.

AoU: keep igv-jupyter on 1.x.x, the most recent known working version

---

config/community_images.json

The RStudio image needs to be updated to 3.15.2 as per this commit https://github.com/anvilproject/anvil-docker/commit/2eb4018718ff105fd1a5373921f8bcc99179877c
https://broadworkbench.atlassian.net/browse/IA-3484

IA-3484 Update community.json RStudio version

---

terra-jupyter-aou/Dockerfile

We started using pip system specifiers (e.g. ; sys_platform != 'win32') which was causing issues with xargs. Writing a file and running on the file seems simpler anyway.

Fix the Hail Dockerfile

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

Ideally we would upgrade the notebook image to Java 11 fully. My previous attempt only half switched from Java 8 to Java 11, causing some complications in the image. Just revert the change for now.

Revert AoU image Java 11 upgrade attempt

---

terra-jupyter-hail/Dockerfile

The version referenced in hail dockerfile is not valid
See changelog for terra-jupyter-python version in question
```
- reverted, do not use
```
Should not require a changelog bump for terra-jupyter-hail since this version was never generated due to error.

[IA-4070] fix hail

---

config/conf.json
terra-jupyter-hail/CHANGELOG.md

The CI is angered that I made changes to hail image without bumping  its version. Need to bump the version to get it to stop failing to build an already-existing image

[IA-4070] Fix terra-docker CI

---

terra-jupyter-aou/Dockerfile

Per Feedback from Sam Bryant at the broad, Bolt LMM 2.4 doesn't exist.

Update Bolt LMM to 2.4.1 because 2.4 doesn't exist. 

---

terra-jupyter-python/Dockerfile
terra-jupyter-r/Dockerfile

It might be a typo in https://github.com/DataBiosphere/terra-docker/pull/394, and it makes `python, gatk, r, aou` images fail to build and push.

[no ticket] Fix docker version because base image v13 does not exist in GCR

---

terra-jupyter-base/custom/jupyter_delocalize.py

https://broadworkbench.atlassian.net/browse/IA-4148
This PR updates the import from notebook to Jupyter Server. 
It seems the package naming changed with the new DSVM image.

[IA-4148] updated the LargeFileManager import in jupyter_delocalize.py

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile

1: The newer Hail version requires higher version of Spark. Spark is intalled via Leonardo. Rollback Hail for now until Leo upgrade Dataproc version. 
2: Fix a typo of Cromshell alias.

[RW-10154][RW-10159] Fix Cromshell alias and revert Hail upgrade

---

config/community_images.json

- Adds Bioconductor 3.17 image with R 4.3.0
- Adds Bioconductor 3.16.1 image as legacy with R 4.2.3
- Both images are now GPU-ready, and images going forward will remain so, and therefore the GPU box can be allowed for all Bioconductor RStudio images not just Custom Environments going forward
- Images have increased in size from 1.8GB to 6.5GB as a result of the new `cuda` base image
Jupyter 3.17 PR will be done separately as per previous requests

Bioconductor RStudio 3.17 release

---

config/conf.json
config/legacy_static_images.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk-ovtf/CHANGELOG.md
terra-jupyter-gatk-ovtf/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Complements https://github.com/DataBiosphere/terra-docker/pull/420 .
Making Jupyter PR before propagation is done for RStudio as discussed with Susan on Slack.

Update to Jupyter for Bioconductor 3.17 release

---

.github/workflows/test-terra-jupyter-gatk.yml
config/conf.json
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile

Silly mistake on my part, bedtools binaries are generated properly, but were not actually moved to an accessible path 😬 
The commands are now identical to bcftools, which is a working command.

[IA-3730] move bedtools binaries to accessible path

---

.github/workflows/publish.yml
config/conf.json
wondershaper/Dockerfile
wondershaper/README.md
wondershaper/entrypoint.sh

I’ve created a wondershaper image and published it to this path https://pantheon.corp.google.com/gcr/images/broad-dsp-gcr-public/us/wondershaper?project=broad-dsp-gcr-public
I think we can still have this PR merged and keep the wondershaper image to use it in the future if needed, despite that we may be using GCE apps instead of GKE in the near future

RW-9307 wondershaper docker image

---

config/legacy_static_images.json

`2.1.10` is the last version with R 4.2.2 and Bioc 3.16.
Since the latest container is Bioc 3.17 and R 4.3.0, it makes sense to leave the legacy at Bioc 3.16, rather than Bioc 3.17 with older python as is `2.1.11`.

Change legacy BiocJupyter to last 3.16 container

---

terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile

Forgot to also remove the installation of Java 8 for the AOU image, we are getting Java 11 form the new debian11 dataproc image in leonardo now, and it conflicts with the Java 8 that was previously installed on the image
Instead of bumping up the version, i am just going to override the existing one since we never released it

IA-4362 remove java 8 for the gatk and aou images and update hail to 120

---

.github/workflows/test-terra-jupyter-base.yml
.github/workflows/test-terra-jupyter-bioconductor.yml
.github/workflows/test-terra-jupyter-hail.yml
.github/workflows/test-terra-jupyter-python.yml
build.sh
config/conf.json
mind.puml
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-python/requirements.txt
terra-jupyter-python/tests/smoke_test.ipynb
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

https://broadworkbench.atlassian.net/browse/ID-721
Updating TNU to `0.13.0` so that the DRSHub can be used instead of Martha. If TNU sees a `DRS_RESOLVER_ENDPOINT` environment variable, it will talk to DRSHub at the specified endpoint for DRS resolutions. If the env var is not provided, TNU will default back to Martha.
Looks like I had to update all the images!

ID-721 Update Terra Notebook Utils to 0.13.0

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

The previous set of images had a version of jupyter notebook and server that seemed to be incompatible (it was boud to happen without pinning dependencies), this should hopefully fix the issue 🤞 
Leo PR: https://github.com/DataBiosphere/leonardo/pull/3797
Note:
- The test failure for the bioconductor image is expected (the thing is too big and times out)
- I have tested all images on my BEE and things are working well

[IA-4586] Regenerate images with known versions of jupyter notebook and server

---

config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile

JIRA ticket: https://broadworkbench.atlassian.net/browse/IA-4661

[IA-4665] Fix gnomad for new hail versions

---

config/community_images.json
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

- Added Bioc 3.19 with R 4.4.0 for latest release.
- Added Bioc 3.18 and R 4.3.3 for RStudio legacy.
- Updated versions for Jupyter Dockerfile and used provided ammonite script to make version bumps.

Update Jupyter and RStudio for 3.19 release

---

.github/workflows/publish.yml
.github/workflows/test-terra-jupyter-aou.yml
.github/workflows/test-terra-jupyter-base.yml
.github/workflows/test-terra-jupyter-bioconductor.yml
.github/workflows/test-terra-jupyter-gatk.yml
.github/workflows/test-terra-jupyter-hail.yml
.github/workflows/test-terra-jupyter-python.yml
CONTRIBUTING.md
config/conf.json
terra-jupyter-aou/CHANGELOG.md
terra-jupyter-aou/Dockerfile
terra-jupyter-base/CHANGELOG.md
terra-jupyter-base/Dockerfile
terra-jupyter-bioconductor/CHANGELOG.md
terra-jupyter-bioconductor/Dockerfile
terra-jupyter-gatk/CHANGELOG.md
terra-jupyter-gatk/Dockerfile
terra-jupyter-hail/CHANGELOG.md
terra-jupyter-hail/Dockerfile
terra-jupyter-python/CHANGELOG.md
terra-jupyter-python/Dockerfile
terra-jupyter-python/requirements.txt
terra-jupyter-python/tests/smoke_test.ipynb
terra-jupyter-r/CHANGELOG.md
terra-jupyter-r/Dockerfile

Use latest version 0.14: https://pypi.org/project/terra-notebook-utils/0.14.0/ which has the following [changes](https://github.com/DataBiosphere/terra-notebook-utils/blob/master/Changes.md#changes-for-v0140-2024-09-03)

[ID-1352] Update TNU version in Dockerfile

---

config/community_images.json

All of our UI integration tests failed after we merged in the new bioconductor image because `RStudio` was changed to `Rstudio`, I definitely missed this during review. This is a very brittle process that we should refactor, but for now, reverting this little change (dev, staging, and prod have been manually fixed).

[AN-304] Do not rename images id as Terra UI depends on it
